name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fmunirdev/envvar-to-dotenv-action@v0.1.0
        env:
          VAR1: hi
        with:
          variableNames: VAR1
      - run: cat .env
